export const hotelTypes = [
  "Luxury",
  "Boutique",
  "Family",
  "Golf Resort",
  "Business",
  "All-Inclusive",
  "Eco-Friendly",
  "Beachfront",
  "Ski Resort",
  "Spa & Wellness",
  "Adults Only",
  "Budget",
  "Historic",
  "Hostel",
  "Villa",
  "Extended Stay",
];

export const hotelFacilities = [
  "Free Wi-Fi",
  "Parking",
  "Swimming Pool",
  "Fitness Center",
  "Spa",
  "Restaurant",
  "Bar",
  "Airport Shuttle",
  "24-Hour Front Desk",
  "Room Service",
];
